version: "3.8"

services:
   ecommerce_db:
      image: postgres:17
      container_name: ecommerce_db
      environment:
         POSTGRES_USER: user
         POSTGRES_PASSWORD: userpass
         POSTGRES_DB: ecommerce_db
      volumes:
         - ecommerce_db_data:/var/lib/postgresql/data
      ports:
         - "5433:5432"

      # 🧠 Recommended resource control
      deploy:
         resources:
            limits:
               # HARD max 1.5 GB RAM
               memory: 1.5G
            reservations:
               # Guarantee 512 MB RAM
               memory: 512M

      healthcheck:
         test: ["CMD-SHELL", "pg_isready -U user -d ecommerce_db"]
         interval: 5s
         timeout: 5s
         retries: 5

   ecommerce_redis:
      image: redis:7.4
      container_name: ecommerce-app-redis-db
      restart: always
      ports:
         - "6379:6379"
      command: redis-server --save 60 1 --loglevel warning
      volumes:
         - ecommerce_redis_data:/data

      # 🧠 Resource limits for Redis
      deploy:
         resources:
            limits:
               memory: 512M
            reservations:
               memory: 256M

      healthcheck:
         test: ["CMD", "redis-cli", "ping"]
         interval: 5s
         timeout: 3s
         retries: 5

volumes:
   ecommerce_db_data: {}
   ecommerce_redis_data: {}
