version: '3.8'

services:
  ecommerce_db:
    image: postgres:17
    container_name: ecommerce_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecommerce_db
    volumes:
      - ecommerce_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    
    # 🧠 Recommended resource control
    deploy:
      resources:
        limits:
          # Sets a HARD maximum of 1.5 GB RAM (prevents "eating" RAM)
          memory: 1.5G 
        reservations:
          # Guarantees the service has 512 MB RAM (ensures "manageable" performance)
          memory: 512M

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d ecommerce_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  # ✅ Definition of the named volume
  ecommerce_db_data: {}