services:
   ecommerce_db:
      image: postgres:17
      container_name: ecommerce_db
      environment:
         POSTGRES_USER: user
         POSTGRES_PASSWORD: userpass
         POSTGRES_DB: ecommerce_db
      volumes:
         - ecommerce_db_data:/var/lib/postgresql/data
      ports:
         - "5433:5432"
      healthcheck:
         test: ["CMD-SHELL", "pg_isready -U user -d ecommerce_db"]
         interval: 5s
         timeout: 5s
         retries: 5

   redis:
      image: redis:7-alpine
      container_name: ecommerce_redis
      ports:
         - "6379:6379"
      volumes:
         - ecommerce_redis_data:/data

volumes:
   ecommerce_db_data: {}
   ecommerce_redis_data: {}
